spring.application.name=notification-service
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

rabbitmq.queuename=${QUEUE_NAME}

rabbitmq.host=${RABBIT_HOST}
rabbitmq.username=${RABBIT_USER}
rabbitmq.password=${RABBIT_PASSWORD}
rabbitmq.port=${RABBIT_PORT}
