spring.application.name=order-service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

rabbitmq.orderqueue=${ORDER_QUEUE}

rabbitmq.host=${RABBIT_HOST}
rabbitmq.username=${RABBIT_USER}
rabbitmq.password=${RABBIT_PASSWORD}
rabbitmq.port=${RABBIT_PORT}
rabbitmq.virtual-host=${RABBIT_VHOST}

springdoc.swagger-ui.use-root-path=true